services:
  kafka:
    image: quay.io/strimzi/kafka:0.47.0-kafka-4.0.0
    command: [
      "sh", "-c",
      "./bin/kafka-storage.sh format --standalone -t $(./bin/kafka-storage.sh random-uuid) -c ./config/server.properties && ./bin/kafka-server-start.sh ./config/server.properties"
    ]
    ports:
    - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
